[workspace]
members = ["realbin/launcher", "realbin/wgpu_renderer"]
resolver = "3"

[package]
name = "framethreader"
version = "0.1.0"
edition = "2024"

[dependencies]
launcher = {path = "realbin/launcher"}
wgpu_renderer = {path = "realbin/wgpu_renderer"}

[workspace.dependencies]
wgpu = "30.0.1"
winit = "0.30.13"
env_logger = "0.11.11"
image = { version = "0.25", default-features = false, features = ["jpeg"] }
pollster = "0.3"
rayon = "1.8"
bytemuck = { version = "1.18", features = ["derive"] }
eframe = "0.36.2"
egui = "0.36.2"
egui_extras = "0.36.2"
rfd = "0.17.2"

[profile.dev.package.image]
opt-level = 3
[profile.dev.package.zune-jpeg]
opt-level = 3
[profile.dev.package.jpeg-decoder]
opt-level = 3