[package]
name = "launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = {workspace = true}
eframe = {workspace = true}
egui_extras = {workspace = true}
env_logger = {workspace = true}
rfd = {workspace = true}
time = {workspace = true}
rayon = {workspace = true}
common = { path = "../../common" }